# .appveyor.yml

# Build version
version: '1.5.7.{build}'

# Use the latest available toolchain
image: Visual Studio 2019

# fetch repository as zip archive
shallow_clone: false

# PRs do not increment the build number
pull_requests:
  do_not_increment_build_number: true

# Environment variables
environment:
  global:
    # See http://donovanbrown.com/post/Stop-wasting-time-during-NET-Core-builds
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    # See https://docs.microsoft.com/en-us/dotnet/core/tools/telemetry#how-to-opt-out
    DOTNET_CLI_TELEMETRY_OPTOUT: true

# Build profiles
configuration:
  - Debug
  - Release

# Inherit AppVeyor version in the built artifacts
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

# Run these scripts before starting build
before_build:
  # Ensure project dependencies are fetched
  - git submodule update --init --recursive
  - nuget restore

# Build configuration
build:
  project: 7thWrapperSln.sln
  verbosity: minimal

# Do not run unit tests
test: off

# Package artifacts
artifacts:
  - path: .dist\Build\Debug
    name: 7thHeaven-v${appveyor_build_version}_debug
    type: zip
  - path: .dist\Build\Release
    name: 7thHeaven-v${appveyor_build_version}
    type: zip

# Create a GitHub release for every tag
deploy:
  - provider: GitHub
    tag: ${appveyor_repo_tag_name}
    release: 7thHeaven-v${appveyor_build_version}
    artifact: 7thHeaven-v${appveyor_build_version}_debug,7thHeaven-v${appveyor_build_version}
    auth_token:
      secure: SXUyBqg8+wl9fn3xHV2Br0xDH65EyPAnFwJbwcg94wIesv9osQEefC3zxu9iDTUh
    on:
      appveyor_repo_tag: true
